In [60]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [49]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [50]:
df=pd.read_csv('Twitter_Data.csv')
df.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [51]:
df.shape

(162980, 2)

In [52]:
df['category'].value_counts()

category
 1.0    72250
 0.0    55213
-1.0    35510
Name: count, dtype: int64

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162980 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   clean_text  162976 non-null  object 
 1   category    162973 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.5+ MB


In [54]:
df.isnull().sum()

clean_text    4
category      7
dtype: int64

In [55]:
df=df.dropna()

In [56]:
corpus=[]
for review in df['clean_text']:
    review=re.sub('[^a-zA-Z]',' ',review)
    review=review.lower().split()
    review=[word for word in review if word not in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)
corpus[-1]

'ever listen like gurukul discipline maintained even narendra modi rss maintaining culture indian attack politics someone attack hinduism rss take action proud'

In [57]:
x=df['clean_text']
y=df['category']

In [61]:
tfidf=TfidfVectorizer()
x=tfidf.fit_transform(x)

In [62]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [63]:
lr_model=LogisticRegression()
lr_model.fit(x_train,y_train)
lr_pred=lr_model.predict(x_test)
print(accuracy_score(y_test,lr_pred))
print(classification_report(y_test,lr_pred))


0.9186046511627907
[[ 5733   652   767]
 [   77 10810   180]
 [  432   545 13398]]
              precision    recall  f1-score   support

        -1.0       0.92      0.80      0.86      7152
         0.0       0.90      0.98      0.94     11067
         1.0       0.93      0.93      0.93     14375

    accuracy                           0.92     32594
   macro avg       0.92      0.90      0.91     32594
weighted avg       0.92      0.92      0.92     32594



/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [65]:
nb_model=MultinomialNB()
nb_model.fit(x_train,y_train)
nb_pred=nb_model.predict(x_test)
print(accuracy_score(y_test,nb_pred))
print(classification_report(y_test,nb_pred))


0.5673436828864208
              precision    recall  f1-score   support

        -1.0       0.95      0.10      0.18      7152
         0.0       0.91      0.32      0.48     11067
         1.0       0.51      0.99      0.67     14375

    accuracy                           0.57     32594
   macro avg       0.79      0.47      0.44     32594
weighted avg       0.74      0.57      0.50     32594



In [ ]:
svm=SVC()
svm.fit(x_train,y_train)
svm_pred=svm.predict(x_test)
print(accuracy_score(y_test,svm_pred))
print(classification_report(y_test,svm_pred))